mvp-download-links: 
  win: "https://onboardcloud.dl.sourceforge.net/project/mpv-player-windows/64bit/mpv-x86_64-20220116-git-1ba0547.7z"
  lin: "https://www.deb-multimedia.org/pool/main/m/mpv-dmo/mpv_0.34.1-dmo2_amd64.deb"
